### ISSUE TITLE
[Feature Request] Centralized Management Location for User-added Organizational Values

### ISSUE THREAD

**Issue by moriel5** [KSSidll/Arru#20]
When adding organizational values (I may be using the wrong term here, English is not my native language, though I speak it pretty much like a native) such as Shops, Producers, Products, Categories and Variants, currently the only way to manage them is by editing a transaction.

It would be very beneficial, if in addition, we had a centralized location to view and manage all such values.

**Comment by KSSidll** [comment]
I feel like what you are looking for is the 'search' accessible through the icon hidden (on smaller screens) in a pullable bottom sheet marked with a hinge in the screen that lists all the transactions, unless I'm misunderstanding.
It centralizes the Producers, Shops, Categories and Products.

There is no place that centralizes the Variants at the moment however, so that might be worth looking into.
