### ISSUE TITLE
Current date don't  select automatically 

### ISSUE THREAD

**Issue by vigneshbalan-mvgs** [KSSidll/Arru#8]
When ever i try to add my expenses to the app it selected the date of which is already used date can you guys change that into current date because it could be helpful

**Comment by KSSidll** [comment]
Currently the date is automatically selected as the date of the last transaction
that works when you collect receipts over few days and then add them all at once

I could change that so that the first transaction after opening the app is set to today and not change it afterwards
That should work for most people, if there's issues after that I will add an option to change this behavior

(not sure why this was closed instantly tho?)
